server:
  port: 8081

spring:
  application:
    name: UserManagementServices
    
 # cloud:
    #stream:
     # bindings:
       #input:
         # content-type: application/json
          #destination:  user-stream 
      # output: 
         # content-type: application/json
            datasource:
    url: jdbc:mysql://192.168.1.164:3306/kings
    username: kings
    password: kings@123
  jpa:
    show-sql: true 
    

#eureka:
 # client:
  #  service-url:
   #   defaultZone: http://localhost:8761//eureka/